name: test

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      env:
        GOOGLE_ACCOUNT_TYPE: ${{ secrets.GOOGLE_ACCOUNT_TYPE }}
        GOOGLE_CLIENT_EMAIL: ${{ secrets.GOOGLE_CLIENT_EMAIL }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        TEST_PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
        TEST_UID: ${{ secrets.TEST_UID }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_WEB_API_KEY: ${{ secrets.TEST_WEB_API_KEY }}
      run: |
        export GOOGLE_PRIVATE_KEY=`echo ${{ secrets.GOOGLE_PRIVATE_KEY_BASE64 }} | base64 -d`
        bundle exec rspec
